apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-frontend-galerias
  annotations:
    # ---------
    # -Considerar si es un servicio que se expone interno o externo
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
    # ---------
    run.googleapis.com/description: Frntend Galerias
spec:
  template:
    metadata:
      annotations:
        # --------- 
        # - Considerar segun lo presupuestado
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 2
        # --------- 
        # --------- 
        # -Considerar para tener conectividad on-prem y/o servicios de google internos
        # run.googleapis.com/vpc-access-connector: projects/corp-dev-net-shared/locations/us-east4/connectors/
        # run.googleapis.com/vpc-access-egress: private-ranges-only
        # ---------
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: $image_tag
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
