name: DEV Deployment Workflow

on:
  push:

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Image Tag
        id: image-tag
        run: |
          tag="my/repo/image:${GITHUB_SHA::8}"
          echo "image_tag=$tag" >> $GITHUB_OUTPUT

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Render cloud run manifest
        run: envsubst < cicd/environments/dev/cloudrun.yaml

      - name: cat
        run: cat cicd/environments/dev/cloudrun.yaml