name: DEV Deployment Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Image Tag
        id: image-tag
        run: |
          tag="my/repo/image:${GITHUB_SHA::8}"
          echo "image_tag=$tag" >> $GITHUB_OUTPUT

      - name: echo
        run: |-
          export image_tag="${{ steps.image-tag.outputs.image_tag }}"

    outputs:
          image_tag: ${{ steps.image-tag.outputs.image_tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render cloud run manifest
        run: |-
          envsubst < cicd/environments/dev/cloudrun.yaml
        env:
          image_tag: ${{ needs.build.outputs.image_tag }}

      - name: cat
        run: cat cicd/environments/dev/cloudrun.yaml